
| distributed init (rank 4): env://, gpu 4
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff9c81b34c0>
Traceback (most recent call last):
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1424, in _shutdown_workers
    self._pin_memory_thread.join()
KeyboardInterrupt: