
| distributed init (rank 7): env://, gpu 7
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7faeca0584c0>
Traceback (most recent call last):
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1424, in _shutdown_workers
    self._pin_memory_thread.join()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt: